server:
  port: 8081
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://${POSTGRES:localhost}:5435/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  #define kafka params as a consumer | kafka properties 9copy), kafka config -> use standard template not replytemplete
  #find kafka listener annotation for config
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: core-banking-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.json.use.type.headers: false
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
kafka:
  topics:
    bank-account-topic:
      name: com.javatech.finance.bankAccount.topic
      partitions: 1
      replicationFactor: 1