server:
  port: 8081
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://${POSTGRES:localhost}:5435/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  datasource2:
    postgres2:
      url: jdbc:postgresql://localhost:5435/postgres
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
