server:
  port: 8082
spring:
  application:
    name: banking-service-module
  config:
    import: optional:configserver:http://${CONFIG_URL:localhost}:8888
  cloud:  #if cant conntec to config server, it will fail, but to just stop application use this
    config:
      fail-fast: true
kafka:
  topics:
    bank-account-topic:
      name: com.javatech.finance.bankAccount.topic
      partitions: 1
      replicationFactor: 1
